### ISSUE TITLE
API for drone comms site

### ISSUE THREAD

**Issue by L42ARO** [usfsoar/NSL_23-24_PayloadEECS#29]
Create an API for the drone comms site, it highlly depends on how the site works. Preferably we should use websockets for stuff like the serial monitor feature

**Comment by Pavan-da-Coder** [comment]
Created, data with the flag `ALTI: ` is flagged as altimeter information in parser.js, and this information is posted to the npm_functions.js file that will draw charts.
Charts are made with d3.js, and prior to testing or usage, the `npm run build` command must be sent to rebuild the `bundle.js` file that is used by `control_panel.html` . This is because I got d3 working with Webpack
